# https://github.com/marketplace/actions/github-action-for-yarn
# Remember, there are not dependencies ATM. And we don't lint, and we don't need to build.

name: Run Tests

on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
