# https://github.com/marketplace/actions/github-action-for-yarn

name: Run Tests

on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      
      - name: Run Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      
      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
